source: https://redistrictingdatahub.org/dataset/georgia-2024-general-election-precinct-level-results-and-boundaries/

In [4]:
!pip install notebook numpy pandas matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: notebook in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (7.4.3)
Collecting numpy
  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting pandas
  Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting matplotlib
  Using cached matplotlib-3.9.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from notebook) (2.16.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from notebook) (2.27.3)
Requirement already satisfied: jupyterlab<4.5,>=4.4.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from notebook) (4.4.3)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from notebook) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from notebook) (6.5.1)
Requirement already satisfied: anyio>=3.1.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (4.9.0)
Requirement already satisfied: argon2-cffi>=21.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (3.1.6)
Requirement already satisfied: jupyter-client>=7.4.4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.8.1)
Requirement already satisfied: jupyter-events>=0.11.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.7.0)
Requirement already satisfied: packaging>=22.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.0)
Requirement already satisfied: prometheus-client>=0.9 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.22.1)
Requirement already satisfied: pyzmq>=24 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (26.4.0)
Requirement already satisfied: send2trash>=1.8.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.18.1)
Requirement already satisfied: traitlets>=5.6.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.14.3)
Requirement already satisfied: websocket-client>=1.7 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (0.28.1)
Requirement already satisfied: importlib-metadata>=4.8.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (8.7.0)
Requirement already satisfied: ipykernel>=6.5.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (6.29.5)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (2.2.5)
Requirement already satisfied: setuptools>=41.1.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (58.0.4)
Requirement already satisfied: tomli>=1.2.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (2.2.1)
Requirement already satisfied: babel>=2.10 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (0.12.0)
Requirement already satisfied: jsonschema>=4.18.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (4.24.0)
Requirement already satisfied: requests>=2.31 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (2.32.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.60.2-cp39-cp39-macosx_10_9_universal2.whl.metadata (113 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.7-cp39-cp39-macosx_11_0_arm64.whl.metadata (6.3 kB)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-11.3.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting importlib-resources>=3.2.0 (from matplotlib)
  Using cached importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (1.3.0)
Requirement already satisfied: idna>=2.8 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (3.10)
Requirement already satisfied: sniffio>=1.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (4.14.0)
Requirement already satisfied: argon2-cffi-bindings in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (21.2.0)
Requirement already satisfied: certifi in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.8.3->jupyterlab<4.5,>=4.4.3->notebook) (3.23.0)
Requirement already satisfied: appnope in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (1.8.14)
Requirement already satisfied: ipython>=7.23.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (8.18.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.1.7)
Requirement already satisfied: nest-asyncio in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (1.6.0)
Requirement already satisfied: psutil in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (7.0.0)
Requirement already satisfied: decorator in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (5.2.1)
Requirement already satisfied: jedi>=0.16 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.19.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (2.19.1)
Requirement already satisfied: stack-data in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.6.3)
Requirement already satisfied: pexpect>4.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (4.9.0)
Requirement already satisfied: wcwidth in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (0.25.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook) (4.3.8)
Requirement already satisfied: python-json-logger>=2.0.4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (6.0.2)
Requirement already satisfied: rfc3339-validator in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.1)
Requirement already satisfied: fqdn in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.5.1)
Requirement already satisfied: isoduration in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (3.0.0)
Requirement already satisfied: uri-template in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (24.11.1)
Requirement already satisfied: beautifulsoup4 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (4.13.4)
Requirement already satisfied: bleach!=5.0.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (6.2.0)
Requirement already satisfied: defusedxml in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.5.1)
Requirement already satisfied: webencodings in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook) (2.21.1)
Requirement already satisfied: ptyprocess>=0.5 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.7.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook) (2.4.0)
Requirement already satisfied: cffi>=1.0.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (1.17.1)
Requirement already satisfied: pycparser in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (2.22)
Requirement already satisfied: soupsieve>1.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (2.7)
Requirement already satisfied: arrow>=0.15.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (2.9.0.20250516)
Requirement already satisfied: executing>=1.2.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (3.0.0)
Requirement already satisfied: pure-eval in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.2.3)
Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
Using cached matplotlib-3.9.4-cp39-cp39-macosx_11_0_arm64.whl (7.8 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.0-cp39-cp39-macosx_11_0_arm64.whl (249 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.60.2-cp39-cp39-macosx_10_9_universal2.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 28.3 MB/s eta 0:00:00
Using cached importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Using cached kiwisolver-1.4.7-cp39-cp39-macosx_11_0_arm64.whl (64 kB)
Using cached pillow-11.3.0-cp39-cp39-macosx_11_0_arm64.whl (4.7 MB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, pyparsing, pillow, numpy, kiwisolver, importlib-resources, fonttools, cycler, pandas, contourpy, matplotlib, seaborn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [seaborn]1/13 [matplotlib]

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
!pip install geopandas
import geopandas

Defaulting to user installation because normal site-packages is not writeable
Collecting geopandas
  Downloading geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: numpy>=1.22 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.0.2)
Collecting pyogrio>=0.7.2 (from geopandas)
  Downloading pyogrio-0.11.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (5.3 kB)
Requirement already satisfied: packaging in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=1.4.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.3.3)
Collecting pyproj>=3.3.0 (from geopandas)
  Downloading pyproj-3.6.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (31 kB)
Collecting shapely>=2.0.0 (from geopandas)
  Downloading shapely-2.0.7-cp39-cp39-macosx_11_0_arm64.whl.metadata (6.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2025.3)
Requirement already satisfied: certifi in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pyogrio>=0.7.2->geopandas) (2025.4.26)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.15.0)
Downloading geopandas-1.0.1-py3-none-any.whl (323 kB)
Downloading pyogrio-0.11.1-cp39-cp39-macosx_12_0_arm64.whl (19.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 32.2 MB/s eta 0:00:00a 0:00:01
Downloading pyproj-3.6.1-cp39-cp39-macosx_11_0_arm64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 19.2 MB/s eta 0:00:00a 0:00:01
Downloading shapely-2.0.7-cp39-cp39-macosx_11_0_arm64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 23.6 MB/s eta 0:00:00
Installing collected packages: shapely, pyproj, pyogrio, geopandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [geopandas]/4 [geopandas]
Successfully installed geopandas-1.0.1 pyogrio-0.11.1 pyproj-3.6.1 shapely-2.0.7

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [ ]:
all_prec_df = pd.read_json("../data/Georgia/Precinct/ga_2024_gen_all_prec.json")
all_prec_df.head()

                type                                           features
0  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Poly...
1  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Poly...
2  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Poly...
3  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Poly...
4  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Poly...

In [10]:
all_prec = geopandas.read_file("../data/Georgia/Precinct/ga_2024_gen_all_prec.json")

In [21]:
all_prec.shape

(2720, 395)

In [15]:
all_prec.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,G24A1NO,G24A1YES,G24A2NO,G24A2YES,G24RFANO,...,GSL175DWIS,GSL175RLAH,GSL176RBUR,GSL177DSHA,GSL177RGRI,GSL178RMEE,GSL179RTOW,GSL180DDAN,GSL180RSAI,geometry
0,APPLING-:-1B,001,Appling,1B,1B,400,515,553,356,452,...,0,0,0,0,0,0,0,0,0,"POLYGON ((375680.6717 3535246.721, 375661.7260..."
1,APPLING-:-1C,001,Appling,1C,1C,324,400,428,284,356,...,0,0,0,0,0,115,0,0,0,"POLYGON ((378692.83305 3524352.95062, 378693.0..."
2,APPLING-:-2,001,Appling,2,2,487,669,626,516,668,...,0,0,0,0,0,0,0,0,0,"POLYGON ((380113.83825 3525064.44313, 380005.7..."
3,APPLING-:-3A1,001,Appling,3A1,3A1,240,351,344,238,271,...,0,0,0,0,0,0,0,0,0,"POLYGON ((377753.85375 3534608.0735, 377772.22..."
4,APPLING-:-3C,001,Appling,3C,3C,439,596,577,444,509,...,0,0,0,0,0,70,0,0,0,"POLYGON ((386469.24138 3520110.56137, 386430.8..."

In [23]:
all_cols = all_prec.columns
print(f"length: {len(all_cols)}")
print(f"all columns: {all_cols}")

length: 395
all columns: Index(['UNIQUE_ID', 'COUNTYFP', 'County', 'PRECINCT_I', 'PRECINCT_N',
       'G24A1NO', 'G24A1YES', 'G24A2NO', 'G24A2YES', 'G24RFANO',
       ...
       'GSL175DWIS', 'GSL175RLAH', 'GSL176RBUR', 'GSL177DSHA', 'GSL177RGRI',
       'GSL178RMEE', 'GSL179RTOW', 'GSL180DDAN', 'GSL180RSAI', 'geometry'],
      dtype='object', length=395)

In [18]:
all_prec['County'].unique()

array(['Appling', 'Atkinson', 'Bacon', 'Baker', 'Baldwin', 'Banks',
       'Barrow', 'Bartow', 'Ben Hill', 'Berrien', 'Bibb', 'Bleckley',
       'Brantley', 'Brooks', 'Bryan', 'Bulloch', 'Burke', 'Butts',
       'Calhoun', 'Camden', 'Candler', 'Carroll', 'Catoosa', 'Charlton',
       'Chatham', 'Chattahoochee', 'Chattooga', 'Cherokee', 'Clarke',
       'Clay', 'Clayton', 'Clinch', 'Cobb', 'Coffee', 'Colquitt',
       'Columbia', 'Cook', 'Coweta', 'Crawford', 'Crisp', 'Dade',
       'Dawson', 'Decatur', 'DeKalb', 'Dodge', 'Dooly', 'Dougherty',
       'Douglas', 'Early', 'Echols', 'Effingham', 'Elbert', 'Emanuel',
       'Evans', 'Fannin', 'Fayette', 'Floyd', 'Forsyth', 'Franklin',
       'Fulton', 'Gilmer', 'Glascock', 'Glynn', 'Gordon', 'Grady',
       'Greene', 'Gwinnett', 'Habersham', 'Hall', 'Hancock', 'Haralson',
       'Harris', 'Hart', 'Heard', 'Henry', 'Houston', 'Irwin', 'Jackson',
       'Jasper', 'Jeff Davis', 'Jefferson', 'Jenkins', 'Johnson', 'Jones',
       'Lamar', 'Lanier', 'Laurens', 'Lee', 'Liberty', 'Lincoln', 'Long',
       'Lowndes', 'Lumpkin', 'Macon', 'Madison', 'Marion', 'McDuffie',
       'McIntosh', 'Meriwether', 'Miller', 'Mitchell', 'Monroe',
       'Montgomery', 'Morgan', 'Murray', 'Muscogee', 'Newton', 'Oconee',
       'Oglethorpe', 'Paulding', 'Peach', 'Pickens', 'Pierce', 'Pike',
       'Polk', 'Pulaski', 'Putnam', 'Quitman', 'Rabun', 'Randolph',
       'Richmond', 'Rockdale', 'Schley', 'Screven', 'Seminole',
       'Spalding', 'Stephens', 'Stewart', 'Sumter', 'Talbot',
       'Taliaferro', 'Tattnall', 'Taylor', 'Telfair', 'Terrell', 'Thomas',
       'Tift', 'Toombs', 'Towns', 'Treutlen', 'Troup', 'Turner', 'Twiggs',
       'Union', 'Upson', 'Walker', 'Walton', 'Ware', 'Warren',
       'Washington', 'Wayne', 'Webster', 'Wheeler', 'White', 'Whitfield',
       'Wilcox', 'Wilkes', 'Wilkinson', 'Worth'], dtype=object)