In [24]:
import pandas as pd
import numpy as np
import geopandas

In [25]:
df_de = geopandas.read_file("../data/Delaware/Precinct/de_nyt.geojson")
df_de = df_de.sort_values(by="GEOID")

columns_needed = ['GEOID', 'geometry']
de_precincts = df_de[columns_needed]
de_precincts['precicnt'] = "Precicnt " + df_de["GEOID"]

/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [26]:
de_precincts

,GEOID,geometry,precicnt
0,10001-11-05,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905...",Precicnt 10001-11-05
1,10001-11-06,"POLYGON ((-75.75449 39.22743, -75.75449 39.227...",Precicnt 10001-11-06
2,10001-11-07,"POLYGON ((-75.69349 39.19968, -75.6935 39.1996...",Precicnt 10001-11-07
3,10001-11-08,"POLYGON ((-75.64732 39.15437, -75.64734 39.154...",Precicnt 10001-11-08
4,10001-11-09,"POLYGON ((-75.74776 39.14335, -75.74776 39.143...",Precicnt 10001-11-09
...,...,...,...
520,10005-41-10,"POLYGON ((-75.23551 38.48005, -75.23551 38.480...",Precicnt 10005-41-10
521,10005-41-11,"POLYGON ((-75.19192 38.47895, -75.19193 38.478...",Precicnt 10005-41-11
522,10005-41-12,"POLYGON ((-75.18948 38.48168, -75.18857 38.482...",Precicnt 10005-41-12
523,10005-41-13,"POLYGON ((-75.19192 38.47895, -75.19191 38.478...",Precicnt 10005-41-13
524,10005-41-14,"POLYGON ((-75.17737 38.53138, -75.17696 38.531...",Precicnt 10005-41-14

In [27]:
df_ga = geopandas.read_file("../data/Georgia/Precinct/ga_nyt.geojson")
ga_precincts = df_ga[columns_needed]
ga_precincts['precicnt'] = "Precicnt " + df_ga["GEOID"]

/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [28]:
ga_precincts

,GEOID,geometry,precicnt
0,13001-4B,"POLYGON ((-82.31151 31.59099, -82.31149 31.590...",Precicnt 13001-4B
1,13001-5B,"POLYGON ((-82.40153 31.69729, -82.40206 31.697...",Precicnt 13001-5B
2,13001-3C,"POLYGON ((-82.13346 31.6308, -82.13346 31.6308...",Precicnt 13001-3C
3,13001-2,"POLYGON ((-82.28049 31.84937, -82.2805 31.8493...",Precicnt 13001-2
4,13001-1B,"POLYGON ((-82.29335 31.94084, -82.29344 31.940...",Precicnt 13001-1B
...,...,...,...
2675,13321-01,"POLYGON ((-83.99673 31.5398, -83.99672 31.5398...",Precicnt 13321-01
2676,13321-09,"POLYGON ((-83.79721 31.72736, -83.7972 31.7276...",Precicnt 13321-09
2677,13321-03,"POLYGON ((-83.73692 31.62228, -83.73693 31.622...",Precicnt 13321-03
2678,13321-15,"POLYGON ((-83.89245 31.64641, -83.89212 31.646...",Precicnt 13321-15
2679,13321-14,"POLYGON ((-83.99673 31.5398, -83.99673 31.5397...",Precicnt 13321-14

In [29]:
print(ga_precincts['precicnt'].isnull().sum())
print(de_precincts['precicnt'].isnull().sum())

0
0

In [30]:
de_precincts.to_file("Delaware_precincts.geojson", driver="GeoJSON")
ga_precincts.to_file("Georgia_precincts.geojson", driver="GeoJSON")

In [31]:
!pip install geopandas topojson

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopandas in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (1.0.1)
Requirement already satisfied: topojson in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (1.10)
Requirement already satisfied: numpy>=1.22 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=1.4.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.3.3)
Requirement already satisfied: pyproj>=3.3.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (3.6.1)
Requirement already satisfied: shapely>=2.0.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2025.3)
Requirement already satisfied: certifi in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pyogrio>=0.7.2->geopandas) (2025.4.26)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.15.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [32]:
from topojson import Topology

In [33]:
gdf_ga = geopandas.read_file("Georgia_precincts.geojson")
gdf_de = geopandas.read_file("Delaware_precincts.geojson")

In [34]:
topology_ga = Topology(gdf_ga)
topology_de = Topology(gdf_de)
# Export TopoJSON
topology_ga.to_json("Georgia_precincts_topo.topojson")
topology_de.to_json("Delaware_precincts_topo.topojson")