In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
import re

# Arkansas NGHIS Districts
Contains racial demographics by census block
https://data2.nhgis.org/

In [3]:
df_ar_block = pd.read_csv("../data/Arkansas/ar-census-block-nghis.csv")
print(f"Arkansas shape: {df_ar_block.shape}")
df_ar_block.head(2)

Arkansas shape: (136422, 267)

/var/folders/v8/ptd2qrdj11bf42tp5y0_42700000gn/T/ipykernel_87728/2607516476.py:1: DtypeWarning: Columns (0: VTDA) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ar_block = pd.read_csv("../data/Arkansas/ar-census-block-nghis.csv")

,GISJOIN,YEAR,STUSAB,GEOID,GEOCODE,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,...,U7D062,U7D063,U7D064,U7D065,U7D066,U7D067,U7D068,U7D069,U7D070,U7D071
0,G05000104801001000,2020,AR,1010000US050014801001000,50014801001000,3,7,Arkansas,5,Arkansas County,...,0,0,0,0,0,0,0,0,0,0
1,G05000104801001001,2020,AR,1010000US050014801001001,50014801001001,3,7,Arkansas,5,Arkansas County,...,0,0,0,0,0,0,0,0,0,0

# Arkansas VTD (Voting Tabulation District) Shape File
##### *Census approximations of precincts.*

The Arkansas GIS Office is pleased to announce we have added two new fields to our Elections Precincts data. 
1) The new VTDST fields correlate with the 2010 and 2020 Census VTD file that is included in the PL 94-171 Redistricting Data Summary Files. 
2) The VTDST can be considered the Census code for a particular Election Precinct and is unique per county only. 
aka: vtdst20 – this is the Census VTDST place for the 2020 Census redistricting files. 


GEOID20 = STATEFP + COUNTYFP + VTDST

https://gis.arkansas.gov/2021/08/18/new-fields-added-to-election-precincts-data

In [4]:
df_vtd = gpd.read_file("../data/Arkansas/ar-tiger-vtd-shp/ar20-tiger-vtd.shp")
print(f"VTD shape: {df_vtd.shape}")
df_vtd.head(5)

VTD shape: (2747, 15)

,STATEFP20,COUNTYFP20,VTDST20,GEOID20,VTDI20,NAME20,NAMELSAD20,LSAD20,MTFCC20,FUNCSTAT20,ALAND20,AWATER20,INTPTLAT20,INTPTLON20,geometry
0,05,119,000101,05119000101,P,Precinct 101,Precinct 101,00,G5240,S,4681480,168193,+34.7085416,-092.3586504,"POLYGON ((-92.38206 34.70425, -92.38137 34.706..."
1,05,119,000126,05119000126,P,Precinct 126,Precinct 126,00,G5240,S,15214501,137719,+34.6245712,-092.3044027,"POLYGON ((-92.3473 34.61168, -92.34688 34.6188..."
2,05,119,000137,05119000137,P,Precinct 137,Precinct 137,00,G5240,S,5626980,67793,+34.7666055,-092.4588068,"POLYGON ((-92.49273 34.77624, -92.4926 34.7763..."
3,05,119,000135,05119000135,P,Precinct 135,Precinct 135,00,G5240,S,6793716,404280,+34.7049573,-092.2601773,"POLYGON ((-92.28413 34.70322, -92.28409 34.703..."
4,05,119,000092,05119000092,P,Precinct 092,Precinct 092,00,G5240,S,1424260,0,+34.7732600,-092.3491413,"POLYGON ((-92.35821 34.77209, -92.35818 34.772..."

In [14]:
print(df_vtd.columns)

Index(['STATEFP20', 'COUNTYFP20', 'VTDST20', 'GEOID20', 'VTDI20', 'NAME20',
       'NAMELSAD20', 'LSAD20', 'MTFCC20', 'FUNCSTAT20', 'ALAND20', 'AWATER20',
       'INTPTLAT20', 'INTPTLON20', 'geometry'],
      dtype='str')

# Election Precinct Map Shape File
https://gis.arkansas.gov/

In [5]:
df_pct = gpd.read_file("../data/Arkansas/ar-precinct-shp/ELECTION_PRECINCTS.shp")
print(f"Arkansas shape: {df_pct.shape}")
df_pct.head(20)

Arkansas shape: (2921, 11)

,OBJECTID,state_fips,county_fip,county_nam,precinct,precinct_c,vdst10,vdst20,SHAPE_STAr,SHAPE_STLe,geometry
0,1,05,067,Jackson,Precinct 03,None,GRDCIT,000015,7.263351e+08,144760.641556,"POLYGON ((654268.444 3945515.663, 654308.75 39..."
1,2,05,027,Columbia,Emerson City,None,EMRSCY,000012,2.569444e+06,6411.191179,"POLYGON ((481730.509 3662895.481, 481730.766 3..."
2,3,05,139,Union,Huttig,None,HUTTIG,000HUT,1.805457e+08,93547.965635,"POLYGON ((572054.178 3664066.159, 572169.466 3..."
3,4,05,117,Prairie,Belcher / Tyler,None,000018,0000BT,2.469019e+08,106893.075111,"POLYGON ((621352.401 3845109.578, 621384.101 3..."
4,5,05,101,Newton,Richland,None,000011,000RIC,1.868986e+08,58112.863541,"POLYGON ((497001.753 3963341.234, 497081.16 39..."
5,6,05,121,Randolph,03 - Butler,None,BUTLER,000003,2.673311e+07,27232.849442,"POLYGON ((672042.802 4007368.145, 672041.503 4..."
6,7,05,149,Yell,05 - Crawford,None,CRAWFO,000005,1.890146e+08,64805.183214,"POLYGON ((460791.952 3860894.307, 464002.678 3..."
7,622,05,149,Yell,04 - Compton,None,COMPTO,000004,5.471528e+07,32425.005477,"POLYGON ((457775.184 3872290.034, 460994.017 3..."
8,807,05,053,Grant,01 - Calvert,None,CALVET,000001,1.521112e+08,80509.737700,"POLYGON ((549850.3 3791628.338, 549902.147 379..."
9,8,05,117,Prairie,Wattensaw City Ward 2,None,000024,000WA2,1.472732e+06,7339.907374,"POLYGON ((641784.66 3851163.131, 641780.981 38..."
10,9,05,089,Marion,Precinct 23,None,000023,0MAP23,8.855708e+07,47321.035271,"POLYGON ((534376.468 4000493.091, 534397.173 4..."
11,10,05,069,Jefferson,0029,None,000029,000029,1.409953e+07,15737.416123,"POLYGON ((596521.06 3772500.377, 596515.453 37..."
12,17,05,107,Phillips,Elaine I,None,ELNWD1,002401,7.419979e+05,3585.470037,"POLYGON ((698038.031 3798438.255, 698036.304 3..."
13,393,05,069,Jefferson,103X,None,000103,000103,6.516436e+05,5313.578040,"POLYGON ((593113.547 3788329.857, 593100.85 37..."
14,11,05,003,Ashley,09 - Hickory Grove,None,000009,000009,2.597992e+08,84018.278983,"POLYGON ((599244.397 3666901.322, 599288.337 3..."
15,320,05,089,Marion,Precinct 14,None,000014,0MAP14,2.377686e+06,10136.608502,"POLYGON ((522551.971 4011982.868, 522449.198 4..."
16,808,05,053,Grant,12 - Merry Green 2,None,MGREN2,000012,5.435013e+07,103328.993472,"MULTIPOLYGON (((551353.672 3798081.888, 551351..."
17,12,05,085,Lonoke,12 - Carlisle City Ward 3,None,000030,000012,2.901487e+06,10157.591787,"POLYGON ((613880.244 3850417.836, 613883.584 3..."
18,13,05,069,Jefferson,0117,None,000117,000117,6.635697e+05,3347.174922,"POLYGON ((593094.757 3785554.895, 593028.604 3..."
19,14,05,057,Hempstead,13 Fulton,None,000009,000013,1.644370e+08,104559.154718,"POLYGON ((430158.56 3729246.38, 430150.627 372..."

In [6]:
df_pct['precinct'].nunique()

2666

### Convert duplicate precinct names
We are seeing an issue with different names for the same precinct

In [7]:
for p in sorted(df_pct['precinct'].dropna().unique()):
    print(p)

0001
0002
0003
0004
0005
0007
0008
0009
001
001 - Auburn
001 - Austin
001-Camden
0010
0011
002
002 - Bentley City
002 - Tarry
002-Camden
0026
0027
0028
0029
003
003 - Welbourne West
003 - Yorktown
003-Camden
0030
0031
0032
0033
0034
0036
0037
004
004 - Cane Creek 1
004 - St Vincent
004-Camden
0040
0041
0045
005
005 - Cane Creek 2
005 - Steele
005-Bearden
0050
0051
0053
0054
0055
0056
0057
0058
0059
006
006 - Choctaw
006-Chidester
006-Menifee City
0060
0061
0062
0064
0065
0066
0067
007
007 - Howard City
007 - Kimbrough
007-East Camden
0073
0074
0075
0076
0077
0078
0079
008
008 - Higgins
008 - Lone Pine / Garnett
008-Louann
0080
0081
0082
0083
0084
0085
0086
0087
0089
009
009 - Cedar Falls
009 - Lone Pine / Mt Home
009-Stephens
0090
0092
0093
0094
01
01 - ALAMO
01 - Albion
01 - Allport City
01 - Annieville
01 - Aplin
01 - Baker
01 - Blackfork
01 - Bluffton
01 - Bowie W1
01 - Brinkley Ward 1
01 - Calvert
01 - Crossett Ward 1
01 - Hughes Ward 1
01 - North St Francis
01 - Ward 1
01 - Warren Ward 1
01 Hope 1
01- MENA
01-1
01-2
01-3
010
010 - Gregory
010 - Mill Creek
010-County 001
0101
0104
0105
0107
0108
011
011 - Griffin
011 - Owen / Glendale
011-County 002
0111
0112
0113
0114
0115
0116
0117
0119
012
012 - Lick Mountain
012 - Owen / Palmyra
012-County 003
0120
0121
0122
0123
0124
0125
0126
0128
013
013 - Smith
013 - Washington East
013-County 004
0130
014
014 - McClaren
014 - Spring 1
014-County 005
015
015 - Howard Rural
015 - Spring 2
015-County 007
0150
0151
016
016 - White Eagle
016 -SE Lincoln Co FD
016-County 008
017
017 - Morrilton Ward 3
017 -Wells Bayou
017-County 010
018
018 - Gould
018 - Morrilton Ward 4
018-County 011
019
019 - Martin
019 -Gould City W1
01A - Rison Inside
01B - Rison Outside
02
02 - Antioch
02 - Ashland
02 - BLACK SPRINGS
02 - Blansett
02 - Bowie W2
02 - Briggsville
02 - Brinkley Ward 2
02 - Bristow
02 - Caroline TWP
02 - Casa
02 - Crossett Ward 2
02 - Davis
02 - Hughes Ward 2
02 - North Cadron Inside
02 - South St Francis
02 - Ward 2
02 - Warren Ward 2
02 BARNETT
02 Hope 2
02- MENA
02-1
02-2
02-3
020
020 - Gould City W2
020 - Morrilton Ward 2
0201
0202
0203
0204
0205
0206
0207
0208
0209
021
021 - Gould City W3
021 - Union
0210
0211
0212
0213
0214
0215
0216
0217
0218
0219
022
022 - Bentley Rural
022 - Grady City W1 & W2
0221
0222
0223
0224
0225
023
023 - Star City W1
023 - Washington West
024
024 - Bird
024 - Star City W2
025
025 - Catholic Point
025 - Star City W3
026
026 - Cane Creek 3
026 - Petit Jean
027
027 - Nichols
028
028 - Old Hickory
029
029 - Morrilton Ward 1
02A - Kingsland Inside
02B - Kingsland Out
03
03 - Austin City
03 - Bald Knob Ward 1
03 - Black River
03 - Bowie W3
03 - Bowman
03 - Brawley
03 - Brinkley Ward 3
03 - Butler
03 - CADDO GAP
03 - Centerville
03 - Cherry Hill
03 - Crossett Ward 3
03 - Dekalb 1
03 - E Oak Bluff & Blue Cane
03 - Hughes Ward 3
03 - North Cadron Outside
03 - Ward 3
03 - Warren Ward 3
03 BRADLEY
03 Hope 3
03- MENA
03-1
03-2
03-3
03-4
030
030 - Welbourne East
0305
0306
0307
0308
0309
031
031 - Menifee Rural
0310
0311
0312
0313
0314
0315
0316
0317
0318
0319
032
0320
0321
0322
0323
0324
0325
0326
0327
0328
0329
033
0330
0331
0332
034
035
036
037
038
039
04
04 - ACORN
04 - Bald Knob Ward 2
04 - Black Rock
04 - Bowie Rural
04 - Butler TWP
04 - CANEY
04 - Cauthron/Oliver
04 - Columbia
04 - Compton
04 - Dekalb 2
04 - Fourche
04 - Harper
04 - Hughes Country
04 - North
04 - North Crossett East
04 - South Cadron Inside
04 - Ward 4
04 - West Oak Bluff
04 CULPEPPER
04 Hope 4
04-1
04-2
040
0401
0403
0404
0405
0406
0407
0408
0409
041
0410
0412
0414
0415
0416
0417
0419
042
0420
0421
0422
0423
0425
0426
043
044
045
0450
0451
0452
0453
0454
0455
046
047
048
049
05
05 - Bald knob Ward 3
05 - Bennett & Lemmons
05 - Boas #1
05 - CENTER
05 - Cabot City Ward 1
05 - Cedar Creek
05 - Clayton McArthur
05 - Collins
05 - Crawford
05 - Current River
05 - Darysaw
05 - Houston
05 - Hudgin
05 - INK
05 - North Crossett West
05 - Rawlison
05 - South
05 - South Cadron Outside
05 HOLLY MOUNTAIN
05 Hope 5
05-1
05-2
05-3
05-4
050
0501
0505
051
0510
052
053
0530
054
055
056
057
058
059
06
06 - BOARD CAMP
06 - Bald Knob TWP
06 - Banks City
06 - Boas #2
06 - Bradshaw & Haywood
06 - Cabot City Ward 2
06 - California
06 - Clayton Reed
06 - Coal/Lafayette
06 - Dalton
06 - Danville
06 - FANNIE
06 - Heth
06 - Hurricane
06 - Kenney
06 - West Crossett Rural
06 - enon
06 CHOCTAW
06 Hope 6
06-1
06-2
06-3
060
0601
0605
061
062
063
064
065
066
067
068
069
07
07 - Banks Rural
07 - Beebe Ward 1
07 - Blackfish
07 - Boas #3
07 - CHERRY HILL
07 - Cabot City Ward 3
07 - Center Post
07 - Clayton Tillar
07 - Dardanelle Outside
07 - Denton
07 - Elevenpoint
07 - HOPPER
07 - Jerome
07 - Johnson
07 - Lake
07 - Lee
07 - VO - Tech
07 Hope 7
07 WEST GRIGGS
07-1
07-2
07-3
070
0701
0705
071
072
073
074
075
076
077
078
079
07A
08
08 - BIG FORK
08 - Beebe Ward 2
08 - Brinkley Township
08 - Cabot City Ward 4
08 - Cache
08 - Clayton
08 - Cooter
08 - Dardanelle Ward 1
08 - Fenter
08 - Foster
08 - Franklin
08 - Hickman Ward 1
08 - Knob
08 - Lacey
08 - MOUNT IDA - IN
08 - Maumelle
08 - Miller
08 - Springhill
08 Bingen
08 CRAIG
08-1
08-2
08-3
08-4
08-5
080
0801
081
082
083
084
085
086
087
088
089
09
09 - Beebe Ward 3
09 - Campbell #1
09 - DALLAS VALLEY/ SHADY
09 - Dardanelle Ward 2
09 - Francis
09 - Franklin
09 - Halley
09 - Hermitage City
09 - Hickman Ward 2
09 - Hickory Grove
09 - Ingram
09 - Liddell & chalk Bluff
09 - MOUNT IDA - OUT
09 - Mar N Box 1
09 - New Tennessee
09 - Niven
09 - Widener County GW
09 - York TWP
09 Blevins
09 CARGILE
09-1
09-2
09-3
09-4
090
0900
0901
0902
091
092
093
094
095
0950
096
097
098
099
1
1-A (Oz Wd 1)
1-B (Oz Wd 3)
1-B1-95
1-B1-98
1-B2-96
1-B2-97
1-B3-99
1-C (Oz Wd 2)
1-C1-108
1-C2-107
1-C3-106
1-F4-104
1-F4-105
1-LV-103
1-SC-100
1-SC-101
1-SC-102
1-SC-94
10
10 - Big Creek
10 - Cache
10 - Campbell #2
10 - Carlisle City Ward 1
10 - Cross Roads
10 - Dardanelle Ward 3
10 - Grassey Inside
10 - Hermitage Rural
10 - Hickman Ward 3
10 - Jackson
10 - Jefferson
10 - Madison
10 - Mar N Box 2
10 - NORMAN - IN
10 - Payne & Swain
10 - Perry
10 - Redland
10 - SHADY GROVE
10 - Widener City GE
10 Columbus
10 DAVIS
10-1
10-2
10-3
10-F1-24
10-F1-31
10-F2-22
10-F2-23
100
100 - Cane Creek
1001
1002
101
101 - Carlton
101 - Clark Crossroads
101 - District 1
102
102 - Carlton 2
102 - Clark City
103
103 - Carlton 3
103 - Clark Rural
103X
104
104 - Carlton Rural
104 - Delaware
105
105 - Driggs
106
106 - Ellsworth
107
107 - Johnson
108
108 - Logan
109
109 - Mountain
11
11 - Bradford Ward 1
11 - Campbell #3
11 - Carlisle City Ward 2
11 - Clarendon Ward 1
11 - Dutch Creek
11 - Eagle Lake
11 - Grassey Outside
11 - Hamburg Ward 3
11 - Hickman Rural East
11 - Janes Creek
11 - Marion South
11 - McFall
11 - Merry Green 1
11 - Mississippi
11 - NORMAN - OUT
11 - Petit Jean
11 - Pollard
11 - ROCKY
11 - Round Pond Mosley GE
11 - Rowell
11 - Ward 1 Precinct 1
11 Cross Roads
11 FORMOSA
11-1
11-2
11-3
11-4
11-5
11-6
11-7
11-8
11-9
11-F1-18
11-F1-19
11-F1-20
11-F1-21
11-F2-17
110
110 - River City
1101
111
111 - River Rural
112
113
113 - Shoal Creek
114
114 - Sht Mtn WD 1
115
115 - Sht Mtn WD 2
116
116 - Sht Mtn WD 3
117
117 - Sht Mtn WD 4
118
118 - Caulksville City
119
119 - Caulksville Rural
11A
11B
12
12 - Bradford Ward 2
12 - Brown & Carpenter
12 - Campbell #4
12 - Carlisle City Ward 3
12 - Clarendon Ward 2
12 - Crockett
12 - Ferguson
12 - Greers Ferry Giles
12 - Hamburg Ward 2
12 - Hickman Rural West
12 - Jersey
12 - Little Black
12 - Merry Green 2
12 - Mitcheville
12 - ODEN - IN
12 - Ozment
12 - POTTER
12 - Rankin
12 - Saline
12 - Ward 1 Precinct 2
12 Deann
12 EAST GRIGGS
12-1
12-2
12-3
12-F1-14
12-F1-15
12-F1-16
12-F4-11
12-F4-12
12-F4-13
12-SC-10
120
120 - Ratcliff City
121
121 - Ratcliff Rural
1210
122
122 - Morrison Bluff
123
124
125
126
127
128
129
13
13 - Bradford Ward 3
13 - Cache & Wilson
13 - Carlisle TWP
13 - Clarendon Ward 3
13 - Dent
13 - Galla Rock
13 - Giles
13 - HATFIELD
13 - Hamburg Ward 1
13 - Hon
13 - Johnsville
13 - Keaton
13 - ODEN - OUT
13 - Okean
13 - Plantersville
13 - Rand W1
13 - River
13 - Rose Creek
13 - Round Pond Mosley GW
13 - Ward 1 Precicnt 3
13 Fulton
13-B2-8
13-B2-9
13-B3-1
13-B4-7
13-F4-1
13-F4-2
13-F4-3
13-F4-4
13-F4-5
13-F4-6
130
1301
1305
131
132
132 - Blue Mountain City
133
133 - Blue Mountain Rural
134
134 - Boone WD 1
135
135 - Boone WD 2
136
136 - Boone WD 3
137
137 - Boone WD 4
138
138 - Cauthron
139
139 - Petit Jean
14
14 - COVE
14 - Cadron
14 - Clark
14 - Cleveland TWP
14 - Dowell
14 - Gilkey
14 - Hamburg Rural
14 - Healing Springs
14 - Hunt
14 - Madison City
14 - Marion
14 - Mill Bayou
14 - PENCIL BLUFF
14 - Rand W2
14 - Reyno
14 - Selma
14 - Simpson 1
14 - Smith
14 - Tyler
14 - Ward 1 Precicnt 4
14 Guernsey
140
140 - Reveille City
141
141 - Reveille Rural
142
143
144
144 - Sugar Creek
145
145 - Washburn
146
146 - Barber
147
147 - Tomlinson
148
149
15
15 - Almyra
15 - Cane
15 - Cleburne
15 - Dortch TWP
15 - Duty
15 - Gravelly
15 - Heber Springs Ward 1
15 - James
15 - Madison Country
15 - Mt. Zion
15 - Nelson
15 - Rand W3
15 - Richardson
15 - SIMS
15 - Simpson 2
15 - Tillar
15 - Union
15 - VANDERVOORT
15 - Whiteoak
15 MOUNTAIN
15 McCaskill
150
151
152
153
154
155
156
157
158
159
16
16 - Chrisp
16 - Cleveland & N Kilgore
16 - Cypress Ridge
16 - Eagle TWP
16 - East Roanoke
16 - Eaton
16 - Heber Springs Ward 2
16 - Herring
16 - Jones/Little Texas
16 - Milo
16 - Rand W4
16 - Tuni
16 - Union Valley
16 - WASHITA
16 - WICKES
16 - Whiteville
16 - Wilmar
16 McNab
160
161
162
163
164
165
166
167
168
169
17
17 - Beech Creek
17 - Bonair
17 - Clay
17 - Dixon Township
17 - England City Ward 1
17 - Flat Creek
17 - GRANNIS
17 - Gleghorn & S Kilgore
17 - Heber Springs Ward 3
17 - Keener
17 - Lamar
17 - Rand Rural
17 - Tennessee
17 - West Roanoke
17 - Winchester
17 - Wye
17 LINN CREEK
17 Ozan
170
171
172
173
174
175
176
177
178
179
18
18 - Cleveland
18 - Duncan Township
18 - England City Ward 2
18 - Heber Springs Ward 4
18 - Jesup
18 - Lamb
18 - Magazine 1
18 - Mist
18 - Parrott
18 - Redfork
18 - Running Lake
18 - Wilmar Ward 1
18 Patmos
180
181
182
183
184
185
186
187
188
189
19
19 - Coffey
19 - England City Ward 3
19 - Fargo
19 - Fountain Hill City
19 - Heber Springs Outside
19 - Lafave
19 - Lawrence
19 - Magazine 2
19 - Newcastle
19 - Richland
19 - Shiloh
19 - Washington
19 - Wilmar Ward 2
19 Perrytown
19 RED RIVER
190
191
192
193
194
195
196
197
198
199
2
2-A (Oz Wd 2)
2-B (Oz Rural)
2-C (Lonelm/Cravens)
2-D (Wallace/Ivy)
2-E(Oz Wd 3)
2-GW-85
2-GW-90
2-GW-91
2-GW-92
2-GW-93
2-SC-82
2-SC-83
2-SC-84
2-SC-86
2-SC-87
2-SC-88
2-SC-89
20
20 - Coldwell
20 - Colt City
20 - England City Ward 4
20 - Fountain Hill Rural
20 - Greenfield Township
20 - Lewis 1
20 - Marion
20 - Mason
20 - McJester
20 - Siloam
20 - Silver Lake
20 - Ward 1
20 Rocky Mound
20 UNION
200
201
201 - District 2
201 - Planters 1
202
202 - Planters 2
203
203 - Planters 3
204
204 - Planters 4
205
205 - Planters Rural
206
207
208
209
21
21 - Colt Country
21 - Crosby
21 - Fletcher TWP
21 - Hindman Township
21 - Lewis 2
21 - Morgan
21 - Morgan Outside
21 - Mountain
21 - Portland City
21 - Prairie
21 - Spring River
21 - Walnut Lake
21 - Ward 2
21 - Ward 2 Precinct 1
21 Saratoga
21 WASHINGTON
210
211
212
213
214
215
216
217
218
219
22
22 - Caldwell City
22 - Cypert
22 - Furlow TWP
22 - Holly Grove Township
22 - Lagrue
22 - Mill Creek
22 - Mountain
22 - Portland Rural
22 - Prairie
22 - Promised Land
22 - Union
22 - Ward 2 Precinct 2
22 - Ward 3
22 Shover Springs
22 WHEELER
220
221
222
223
224
225
226
226X
227
228
229
23
23 - Boydell
23 - Caldwell Country
23 - Denmark
23 - East Peter Creek
23 - Goodrum TWP
23 - Mountain
23 - Reeds Creek Saffell
23 - Richland
23 - St. Charles
23 - Ward 2 Precinct 3
23 - Warm Springs
23 MOUNTAIN RANCH
23 Spring Hill
230
231
232
233
234
235
237
238
239
24
24 - Des Arc
24 - Gray TWP
24 - Jackson Township
24 - Mt. Pleasant
24 - Reeds Creek Strawberry
24 - Snyder / Trafalgar
24 - Water Valley
24 - Waveland
24 - West Peter Creek
24 SOUTH GRIGGS
24 Washington
24-Bonair
240
241
242
243
244
245
246
247
248
249
25
25 - Dogwood TWP
25 - Gumwood TWP
25 - Keevil Township
25 - Montrose City
25 - Parks
25 - Pickens
25 - Richwoods
25 - Riley
25 - Wiley
25 INDIAN HILLS
25-Parrot/Newcastle
250
251
252
253
254
255
256
257
258
259
26
26 - Bonair
26 - El Paso
26 - Hamilton TWP
26 - Montgomery/Smalley Townsh
26 - Montrose Rural
26 - Pine
26 - Rover
26 - Spring River
26 - Tomlinson/Tate
26 - Ward One
26 LAKEWOOD
26-Forrest City Country West
260
261
262
263
264
265
266
267
268
269
27
27 - Crooked Creek TWP
27 - Francure
27 - Parkdale City
27 - Pine Ridge Township
27 - Pine Tree
27 - Piney
27 - Strawberry
27 - Ward Two
270
271
272
273
274
275
276
277
278
279
27A
28
28 - Garner TWP
28 - Humnoke City
28 - Palestine City 1
28 - Parkdale Rural
28 - Poff
28 - Raymond Township
28 - Thacker
28 - Ward
28 - Ward Three
280
281
282
283
284
285
286
287
288
289
29
29 - Demun Rural
29 - Garner City
29 - Indian Bayou TWP
29 - Ions Creek
29 - Palestine City 2
29 - Richland Township
29 - Saline Inside
29 - Wilmot City
29-1
29-2
29-3
290
291
292
293
294
295
296
297
298
299
3
3-A (Lonelm/Cravens)
3-B (Fern)
3-BZ-79
3-BZ-80
3-BZ-81
3-C (Boston)
3-D (Jethro)
3-E (Watalula)
3-F (Mountain)
3-HC-78
3-HF-77
3-HG-76
3-MD-75
3-MN-74
3-SC-70
3-SC-71
3-SC-72
3-SC-73
30
30 - Coy City
30 - Gravel Hill
30 - Palestine City 3
30 - Roc-Roe Township
30 - Saline Outside
30 - Wilmot Rural
300
301
301 - Bowie 1
301 - District 3
302
302 - Bowie 2
303
303 - Bowie 3
304
304 - Bowie Rural
305
306
307
308
309
30A
31
31 - Chester
31 - Gray A
31 - Isbell TWP
31 - Palestine Country
31 - Roc-Roe Township/City
31 - Sugar Camp
31 - Ward 3 Precinct 1
310
311
312
313
314
315
316
317
318
319
32
32 - Arkansas
32 - Goodwin
32 - Gray B
32 - Lafayette TWP
32 - Sugar Loaf
32 - Ward 3 Precinct 2
320
321
322
323
324
325
326
327
328
329
33
33 - Griffithville City
33 - Keo City
33 - Stanley
33 - Valley
33 - Ward 3 Precinct 3
33 - Wheatley City
330
331
332
333
334
335
336
337
338
339
34
34 - Gillett Ward 1
34 - Gum Springs
34 - Lonoke City Ward 1
34 - Wheatley Country
34 - Wilburn
340
341
342
343
344
345
346
347
348
349
35
35 - Forrest City Ward 1-1
35 - Gillett Ward 2
35 - Guthrie
35 - Lonoke City Ward 2
35 - Morgan Inside
350
351
352
353
354
355
356
357
358
359
36
36 - Gillett Ward 3
36 - Harrison
36 - Lonoke City Ward 3
360
361
362
363
364
365
366
367
368
369
37
37 - Hartsell
37 - Lonoke City Ward 4
37 - PT Deluce
37-1
37-2
370
371
372
373
374
375
376
377
378
379
38
38 - Bayou Meto
38 - Forrest City Ward 1-4
38 - Higginson TWP
38 - Lonoke TWP
380
381
382
383
384
385
386
387
388
389
39
39 - Higginson  Ward 1
39 - Magness TWP
390
391
392
393
394
395
397
398
399
39A
4
4-A (Philpot)
4-B (Watalula)
4-C (WV Rural)
4-D (Oz Rural)
4-F3-66
4-F3-67
4-F3-68
4-F3-69
4-F4-65
4-GW-62
4-GW-63
4-GW-64
4-HC-61
4-SC-53
4-SC-54
4-SC-55
4-SC-56
4-SC-57
4-SC-58
4-SC-59
4-SC-60
40
40 - Forrest City  Ward 2-1
40 - Jackson
40 - Oak Grove TWP
400
401
401 - District 4
402
403
404
405
406
407
408
409
41
41 - Forrest City Ward 2-2
41 - Jefferson
41 - Morris
41 - Pettus TWp
41 - Ward 4 Precinct 1
410
411
412
413
413X
414
415
416
417
418
418X
419
42
42 - Gum Pond
42 - Joy
42 - Prairie TWP
42 - Ward 4 Precinct 2
420
421
422
423
424
424X
425
426
427
428
429
43
43 - Barton
43 - Forrest City Ward 2-3
43 - Judsonia Ward 1
43 - Pulaski TWP
430
431
432
433
434
435
436
437
438
439
44
44 - Henton
44 - Judsonia Ward 2
44 - Richwood TWP
440
441
442
443
444
445
446
447
448
449
45
45 - Brewer
45 - Forrest City Ward 2-4
45 - Judsonia Ward 3
45 - Totten TWP
450
451
452
453
454
455
456
457
458
459
46
46 - Garland
46 - Kensett Ward 1
46 - Walls TWP
460
461
462
463
464
465
466
467
46A
47
47 - Humphrey Ward 1
47 - Kensett Ward 2
47 - Ward City Ward 1
48
48 - Humphrey Ward 3
48 - Kensett Ward 3
48 - Ward City Ward 2
49
49 - Kensett TWP
49 - Ward City Ward 3
49- Forrest City Ward 3-1
5
5-A (Wallace/Ivy)
5-B (Oz Rural)
5-C (Webb City)
5-F3-50
5-F3-51
5-F3-52
5-F4-48
5-F4-49
5-SC-46
5-SC-47
50
50 - Forrest City Ward 2-2
50 - Kentucky
50 - Ward TWP
501 - District 5
503 - District 5 -
50A
51
51 - DeWitt 1
51 - Letona
51 - Ward 5 Precinct 1
51 - Williams TWP
52
52 - Forrest City Ward 3-4
52 - Liberty
52 - Ward 5 Precinct 2
53
53 - Dewitt 2
53 - Forrest City Ward 3-5
53 - Lonoke City Ward 5
53 - Marion
54
54 - East Black Oak
54 - Lonoke City Ward 6
54 - Marshall
54A
55
55 - Dewitt 3
55 - Forrest City Ward 2-6
55 - Lonoke City Ward 7
55 - McRae Ward 1
55- West Black Oak
56 - Bob Ward 1
56 - Forrest City Ward 4-2
56 - Lonoke City Ward 8
56 - McRae Ward 2
57 - Forrest City Ward 1-6
57 - McRae TWP
57 - North Fogleman
58 - Mt. Pisgah
58 - South Fogleman
59 - Earle Ward 1
59 - Pangburn Ward 1
6
6-A (Altus Rural)
6-B (Altus City)
6-C (Denning)
6-D (Weiderkehr Village)
6-F3-42
6-F3-43
6-F3-44
6-F3-45
6-F4-40
6-F4-41
6-SC-38
6-SC-39
60 - Earle Ward 2
60 - Pangburn Ward 2
601 - District 6
602- District 6
603 - District 6
61 - Earle Ward 3
61 - Red River
610-1
62 - Earle Ward 4
62 - Rose Bud City
620-1
63 - Jackson 1
63 - Royal
64 - Jackson 2
64 - Russell City
65 - Forrest City Ward 4-5
65 - Jasper Country Box (Court
65 - Russell TWP
66 - Forrest City Ward 4-6
66 - Mound City
66 - Searcy Ward 1 A
67 - Jasper 1
68 - Jasper 2
68 - Searcy Ward 1 C
69 - Jasper 3
69 - Searcy Ward 1 D
7
7-A (Cecil)
7-B (Webb City)
7-C (Etna)
7-D (Donald Rural)
7-F1-37

7-F3-34
7-F3-35
7-F3-36
7-F4-32
7-F4-33
70 - Lucas
701 - District 7
703 - District 7
704 - District 7
71 - Searcy Ward 2 B
71 - Stuttgart 1
71-Mississippi Country Box
711-1
712-1
713-1
714-1
72 - Proctor
72 - Searcy Ward 2 C
721-1
73 - North Tyronza
73 - Searcy Ward 2 D
731-1
732-1
733-1
74 - Searcy Ward 3 A
74 - South Tyronza
75 - Jasper County Box, Sunset
75 - Searcy Ward 3 B
76 - Searcy Ward 3 C
76 - Wappanocca
77 - Searcy Ward 3 D
77- Lucas Estate (H'shoe Lake)
78 - Jasper Country Box (Lakes
78 - Searcy Ward 4 A
79 - Bob Ward 2
79 - Searcy Ward 4 B
8
8-A (Branch City)
8-B (Charleston Wd 1)
8-C (Charleston Rural)
8-D (Vesta)
8-E (Donald Rural)
8-F (Cecil)
8-F1-31
8-F2-28
8-F2-29
8-F2-30
8-G (Donald Rural)
80 - Searcy Ward 4 C
80 - Wappanocca, Jericho
801- District 8
802 - District 8
81 - Searcy Ward 2 E
81 - South Tyronza, Jeanette
81 - Stuttgart 2
810-1
82 - Union
82 - Wappanocca, Clarkdale
820-1
83 - Velvet Ridge
830-1
84 - Walker
85 - West Point
86 - Georgetown City
87 - Bald Knob North
88X
9
9-A (Charleston Wd 2)
9-B (Charleston Wd 3)
9-C (Charleston Rural)
9-F1-27
9-F2-25
9-F2-26
90 - Beebe Ward 3 C
901 - District 9
902 - District 9
91 - Harrison East
91 - Stuttgart 3
91X
92 - Searcy Ward 1 E
93 - Searcy Ward 3 E
94 - Pangburn Ward 3
95 - Higginson Ward 2
96 - Higginson Ward 3
Alabam
Amity City
Angora Mtn
Antioch
Arbanna
Arden Township
Arkadelphia Ward 1
Arkadelphia Ward 2
Arkadelphia Ward 3
Arkadelphia Ward 4
Arkadelphia Ward 5
Arkinda Township
Ashdown Ward 1
Ashdown Ward 2
Ashdown Ward 3
Augusta - 01
Augusta - 02
Augusta - 03
Aurelle
Bear Creek
Bear Creek #4
Bear Creek #5
Bear Creek #6
Belcher / Tyler
Ben
Benton - Union
Berryville East
Berryville West
Bethany
Big Creek
Big Spring
Bismarck
Bluff City
Bluff City Rural
Bodcaw City
Bodcaw Rural
Bolivar North
Bolivar South
Bolivar Ward 1
Bolivar Ward 2
Bolivar Ward 3
Bolivar Ward 4
Boston
Boswell
Bright Star
Brockwell
Brown Springs
Brush Creek
Bullard
Burke Township
Bush
Butterfield
Caddo Valley Ward 1
Caddo Valley Ward 2
Caddo Valley Ward 3
Caledonia
Calf Creek
Calhoun
Calico Rock Rural
Calico Rock Ward 1
Calico Rock Ward 2
Calico Rock Ward 3
Calico Rock Ward 4
Calion
Cane Hill-1
Cane Hill-2
Caney Township
Cave
Center
Center-1
Center-2
Center-3
Center-4
Center-5
Central
Central 1
Chambersville
Chambersville West
Champagnolle
Cherokee
Cherokee Village
Cherry Valley
Claiborne
Clear Creek
Cleburne I
Cleburne II
Cleveland
Cleveland Township
College Hill
Columbia North
Columbia South
Cotton Plant - 08
Cotton Plant - 09
Cotton Plant/ Freeman - 07
Country Box # 1
Country Box # 2
Country Box # 3
Country Box # 4
Country Box # 6
Country Box # 7
Cove Creek-1
Cove Creek-3