In [9]:
import pandas as pd

In [12]:
import geopandas as gpd
gdf = gpd.read_file('../../inputs/ga_seawulf.gpkg')

In [19]:
df = pd.read_csv('../Georgia/ga_vra_5000_summary.csv')
df_rb = pd.read_csv('../Georgia/ga_raceblind_5000_summary.csv')

In [15]:
print(df.shape)
df.head()

(5000, 6)

,plan_id,democrat_wins,republican_wins,minority_effective,opportunity_districts,ensemble
0,0,5,9,5,4,vra
1,1,5,9,5,4,vra
2,2,5,9,5,3,vra
3,3,5,9,5,3,vra
4,4,5,9,5,2,vra

In [20]:
print(df_rb.shape)
df_rb.head()

(5000, 6)

,plan_id,democrat_wins,republican_wins,minority_effective,opportunity_districts,ensemble
0,0,5,9,5,4,raceblind
1,1,5,9,5,3,raceblind
2,2,5,9,5,3,raceblind
3,3,5,9,5,3,raceblind
4,4,5,9,5,2,raceblind

In [21]:
democrat_win = (df['democrat_wins'] > df['republican_wins']).sum()
print(f'vra total of {democrat_win} democrat wins')

democrat_win_rb = (df_rb['democrat_wins'] > df_rb['republican_wins']).sum()
print(f'rb total of {democrat_win_rb} democrat wins')

vra total of 22 democrat wins
rb total of 0 democrat wins

In [17]:
minority_effective = df.groupby(['minority_effective']).size()
minority_effective

minority_effective
5    4607
6     390
7       3
dtype: int64

In [22]:
minority_effective_rb = df_rb.groupby(['minority_effective']).size()
minority_effective_rb

minority_effective
2      10
3    1150
4    2097
5    1609
6     134
dtype: int64

In [18]:
opportunity_effective = df.groupby(['opportunity_districts']).size()
opportunity_effective

opportunity_districts
0       2
1     631
2    3221
3     966
4     173
5       7
dtype: int64

In [23]:
opportunity_effective_rb = df_rb.groupby(['opportunity_districts']).size()
opportunity_effective_rb

opportunity_districts
0       6
1     717
2    2783
3    1315
4     179
dtype: int64