## Georgia Box Whisker Plot Data

### Imports

In [1]:
import pandas as pd
import json

### District Data Path to DataFrame

In [2]:
path = '../output/Arkansas/ar-district-CVAP.csv'

In [3]:
district_cvap = pd.read_csv(path)
district_cvap

,Unnamed: 0,State,District,Total CVAP,White CVAP,Black CVAP,Latino CVAP,Other CVAP
0,0,Arkansas,1,568995,446068,90719,13902,18306
1,1,Arkansas,2,569348,414225,114846,19625,20652
2,2,Arkansas,3,543233,436910,14522,52980,38821
3,3,Arkansas,4,564359,411979,110143,23680,18557

In [4]:
district_cvap.drop(columns=['Unnamed: 0', 'State'], inplace=True)
district_cvap

   District  Total CVAP  White CVAP  Black CVAP  Latino CVAP  Other CVAP
0         1      568995      446068       90719        13902       18306
1         2      569348      414225      114846        19625       20652
2         3      543233      436910       14522        52980       38821
3         4      564359      411979      110143        23680       18557

### Race CVAP Enacted Plan Points

In [5]:
dfs = [None, None, None, None]
groups = ['White', 'Black', 'Latino', 'Other']

In [6]:
def calculate_enacted_points(dfs, groups):
    for i, group in enumerate(groups):
        df = district_cvap[['Total CVAP', f'{group} CVAP']]
        df = df.sort_values(by=f'{group} CVAP').reset_index().drop(columns='index').reset_index()
        df['share'] = df[f'{group} CVAP'] / df['Total CVAP']
        df = df[['share']]

        dfs[i] = df
 
calculate_enacted_points(dfs, groups)

for df in dfs:
    print(df)

      share
0  0.729995
1  0.727543
2  0.804277
3  0.783958
      share
0  0.026733
1  0.159437
2  0.195165
3  0.201715
      share
0  0.024433
1  0.034469
2  0.041959
3  0.097527
      share
0  0.032173
1  0.032882
2  0.036273
3  0.071463

In [7]:
white_share = dfs[0].to_dict()
black_share = dfs[1].to_dict()
latino_share = dfs[2].to_dict()
other_share = dfs[3].to_dict()

ar_enacted_shares = {'white': white_share, 'black': black_share, 'latino': latino_share, 'other': other_share}

In [8]:
with open('../output/Arkansas/ar-enacted-shares.json','a') as file:
    file.write(json.dumps(ar_enacted_shares,indent=4))

### Validation

In [9]:
with open('../output/Arkansas/ar-enacted-shares.json') as json_file:
    data = json.load(json_file)

data

{'white': {'share': {'0': 0.7299945602001563,
   '1': 0.727542733091185,
   '2': 0.8042773542844415,
   '3': 0.783957679768715}},
 'black': {'share': {'0': 0.026732543862394223,
   '1': 0.15943725340292972,
   '2': 0.1951647798652985,
   '3': 0.20171494411151}},
 'latino': {'share': {'0': 0.024432552131389555,
   '1': 0.03446925254852919,
   '2': 0.041959107589318145,
   '3': 0.09752721208026759}},
 'other': {'share': {'0': 0.0321725146969657,
   '1': 0.032881552345227064,
   '2': 0.036273070248775796,
   '3': 0.0714628897728967}}}